baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Adil Kassim'
theme = 'PaperMod'

[params]
  defaultTheme = "dark" # light | dark | auto

  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = """
    My name is Adil Kassim, and welcome to my personal website!
    I am very excited to share my projects and thoughts with you.
    Feel free to explore and connect with me on social media.
    """

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/adilkassim"
    icon = "github"